FROM python:3.12.6-alpine3.20

WORKDIR /app

COPY requirements.txt /app/

RUN apk --update --no-cache add python3-dev libpq-dev postgresql postgresql-contrib

RUN pip install --upgrade pip

COPY . /app/

CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000
